#!/usr/bin/perl

# use Data::Dumper;
# use IO::File;
#
# # log file
# my $fd = new IO::File ">>/tmp/tmux-wakatime.log";

# tmux display name
my $tmux = `tmux display-message -p '#W'`;
chomp($tmux);

# path
my $path = $ARGV[0];

my $gitname;
# if we are in a Git dir
if ($path =~ /Git/) {
  chdir($path);
  my $gitexec = 'git remote -v | head -n1 | awk \'{print $2}\' | sed -e \'s,.*:\(.*/\)\?,,\' -e \'s/\.git$//\'';
  $gitname = `$gitexec`;
  chomp($gitname);
  my $tmuxexec = 'tmux rename-window "' . $gitname . '"';
  system("$tmuxexec &");
}

# # command
# my $command = $ARGV[1];
# $command = 'shell' if $command eq '';

if ($gitname eq ''){
  my $exec = "wakatime --write --plugin \"tmux-wakatime/0.0.1\" --entity-type app --project \"Terminal\" --alternate-language fish --entity \"shell\"";

  system("$exec &");
} else {
  my $exec = "wakatime --write --plugin \"tmux-wakatime/0.0.1\" --entity-type app --project \"$gitname\" --alternate-language fish --entity \"shell\"";

  system("$exec &");
}

# $fd->print('git: ' . $gitname . "\n");
# $fd->print('path: ' . $path . "\n");
# $fd->print('preexec: ' . $exec . "\n");
